package com.example.readinglist.controller;

import com.example.readinglist.model.User;
import com.example.readinglist.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with '/demo' (after Application path)
public class UserController {

    // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we'll use it to handle the data
    final UserRepository userRepository;

    @Autowired
    public UserController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    @PostMapping("/add") // Map ONLY POST requests
    public @ResponseBody String addNewUser(@RequestParam String name, @RequestParam String email) {
        // @ResponseBody means the returned String is a response not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);

        userRepository.save(n);

        return "Saved";
    }

    @GetMapping("/main")
    public String addingNewUserPage() {
        return "user";
    }

    @GetMapping("/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
